import builtins from "builtin-modules";
import { defineConfig, type UserConfig } from "vite";

const banner = `
/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(async ({ mode }) => {
	const prod = mode === "production";

	return {
		plugins: [],
		build: {
			lib: {
				entry: "src/main.ts",
				name: "main",
				fileName: () => "main.js",
				formats: ["cjs"],
			},
			minify: prod,
			sourcemap: prod ? false : "inline",
			cssCodeSplit: false,
			emptyOutDir: false,
			outDir: "",
			rollupOptions: {
				input: {
					main: "src/main.ts",
				},
				output: {
					exports: "named",
					entryFileNames: "main.js",
					assetFileNames: "styles.css",
					format: "cjs",
					banner: banner,
				},
				define: {
					DEV: (!prod).toString(),
				},
				dropLabels: prod ? ["DEV"] : [],
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtins,
				],
			},
		},
	} as UserConfig;
});
