on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release

jobs:
    release-please:
        uses: ./.github/workflows/release-please.yml
        with:
            beta: false
        secrets: inherit

    release-please-beta:
        uses: ./.github/workflows/release-please.yml
        with:
            beta: true
        secrets: inherit
