on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please-beta

jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            upload_url: ${{ steps.release.outputs.upload_url }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
          - if: ${{ ! secrets.RELEASE_PLEASE_TOKEN }}
            run: |
                echo 'the secret "RELEASE_PLEASE_TOKEN" has not been made'
                echo 'go to "settings \> secrets \> actions" to create it'
                echo 'falling back to "GITHUB_TOKEN"'

          - uses: googleapis/release-please-action@v4
            id: release
            with:
                token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
                config-file: release-please-config-beta.json
                manifest-file: .release-please-manifest-beta.json

    upload-build:
        runs-on: ubuntu-latest
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        steps:
          - uses: actions/checkout@v4
            ref: ${{ needs.release-please.outputs.tag_name }}

          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
                node-version: "18.x"

          - name: Build plugin
            run: |
                npm install
                npm run build

          - name: Upload release artifacts
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./main.js ./manifest.json ./styles.css
