on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please-beta

jobs:
    release-please:
        runs-on: ubuntu-latest
        env:
            release_please_token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            upload_url: ${{ steps.release.outputs.upload_url }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
          - name: Missing token
            if: ${{ !env.release_please_token }}
            run: |
                printf \
                    '::warning title=%s::%s\n' \
                    'the secret "RELEASE_PLEASE_TOKEN" has not been made' \
                    'falling back to "GITHUB_TOKEN" (go to "settings > secrets > actions" to create RELEASE_PLEASE_TOKEN)'

          - name: Create release
            id: release
            uses: googleapis/release-please-action@v4
            with:
                token: ${{ github.token }}
                config-file: release-please-config-beta.json
                manifest-file: .release-please-manifest-beta.json

    upload-build:
        runs-on: ubuntu-latest
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        steps:
          - uses: actions/checkout@v4
            with:
                ref: ${{ needs.release-please.outputs.tag_name }}

          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 18

          - name: Build plugin
            run: |
                npm install
                npm run build

          - name: Upload release artifacts
            env:
                GITHUB_TOKEN: ${{ github.token }}
                TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
            run: gh release upload ${{ env.TAG_NAME }} ./main.js ./manifest.json ./styles.css
