name: Stage beta release

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "release-please"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
    with:
      beta: true
