name: Stage beta release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
    with:
      beta: true
